version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./
      target: base
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true 
    command: /bin/bash
    ports:
      - "3000:3000"
    restart: 'unless-stopped'
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27018
      MONGO_DATABASE: wefox
    networks:
      - backend
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    command: mongod --port 27018
    ports:
        - '27018:27018'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
